// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOA11dWcUObq_KgNwufhZD1eDttTlUw4g',
    appId: '1:814659311152:web:e882e41c79ed868aca7ff5',
    messagingSenderId: '814659311152',
    projectId: 'doctorhunt-946cf',
    authDomain: 'doctorhunt-946cf.firebaseapp.com',
    storageBucket: 'doctorhunt-946cf.firebasestorage.app',
    measurementId: 'G-X20EPFWREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnTzztdZIk5LcD7iDU-aSuFt7Z_fHCIA',
    appId: '1:814659311152:android:8f42568390346abeca7ff5',
    messagingSenderId: '814659311152',
    projectId: 'doctorhunt-946cf',
    storageBucket: 'doctorhunt-946cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqSQfcJSr8ARnLxCXyIyrOguyaqnESrw',
    appId: '1:814659311152:ios:717b247c1ad351e9ca7ff5',
    messagingSenderId: '814659311152',
    projectId: 'doctorhunt-946cf',
    storageBucket: 'doctorhunt-946cf.firebasestorage.app',
    iosClientId: '814659311152-arm2ft8g7aefj30c9bffp0u86a3vtm5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorhunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqSQfcJSr8ARnLxCXyIyrOguyaqnESrw',
    appId: '1:814659311152:ios:717b247c1ad351e9ca7ff5',
    messagingSenderId: '814659311152',
    projectId: 'doctorhunt-946cf',
    storageBucket: 'doctorhunt-946cf.firebasestorage.app',
    iosClientId: '814659311152-arm2ft8g7aefj30c9bffp0u86a3vtm5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorhunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOA11dWcUObq_KgNwufhZD1eDttTlUw4g',
    appId: '1:814659311152:web:b32132bae02731c1ca7ff5',
    messagingSenderId: '814659311152',
    projectId: 'doctorhunt-946cf',
    authDomain: 'doctorhunt-946cf.firebaseapp.com',
    storageBucket: 'doctorhunt-946cf.firebasestorage.app',
    measurementId: 'G-W7BGB8NPRC',
  );
}
